### ISSUE TITLE
Refactor OntoUploader into an Interface

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/eskg#15]
The [OntoUploader.java](https://github.com/ESIPFed/eskg/blob/master/src/main/java/org/esipfed/eskg/portalservice/OntoUploader.java) code should be refactored into an Interface with individual implementations for both [ESIP COR](http://cor.esipfed.org/) **AND** [ESIP Semantic Portal](http://semanticportal.esipfed.org/). The implementation should be driven by a configuration file which is read from [src/main/resources](https://github.com/ESIPFed/eskg/tree/master/src/main/resources) via an InputStream. All credentials for interfacing with the various ontology repositories should also then be added there as well.

**Comment by graybeal** [comment]
You may find useful a bit of CEDAR's terminology server (https://github.com/metadatacenter/cedar-terminology-server), particular the part that submits value sets to BioPortal. (Unfortunately, no code in there to submit _ontologies_ to BioPortal.)
API documentation at https://terminology.metadatacenter.net/api/, particularly https://terminology.metadatacenter.net/api/#!/Value32sets/put_value_sets_id for submitting the value sets.

**Comment by lewismc** [comment]
@graybeal thank you Sir.

**Comment by lewismc** [comment]
@Yongyao do you want to take this issue on? I am working on #13

**Comment by lewismc** [comment]
After we do that, I think we should release 0.1 to Maven Central.
