### ISSUE TITLE
README link dead?

### ISSUE THREAD

**Issue by trashbirdecology** [ESIPFed/eskg#21]
Should a data source be presented at [this website](http://cor.esipfed.org/ont/eskg/), as is mentioned in the readme?

> The dataset URI is http://cor.esipfed.org/ont/eskg/

**Comment by lewismc** [comment]
Hi @trashbirdecology apologies for delayed reply.
Thank you for pointing this out, I just updated the hyperlink. It now points to http://cor.esipfed.org/ont/eskg/PODAACDataset
Thank you
