### ISSUE TITLE
Get OpenIE running as an Any23 extractor

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/eskg#3]
We could greatly improve the Any23 library by having [OpenIE](https://github.com/allenai/openie-standalone) run as an extractor and generating triples. One of us should look into hooking this up such that we can use the core Any23 API's conveniently within ESKG.

**Comment by Yongyao** [comment]
I have written some Java code with OpenIE before. It probably makes more sense if I do this.

**Comment by lewismc** [comment]
We should also experiment working with the XPath extractor
http://any23.apache.org/apidocs/org/apache/any23/extractor/xpath/XPathExtractor.html
We immediately should be looking to extract structured relationships from the primary dataset landing Information Tab. I've attached a screenshot of the area.
![screen shot 2017-02-01 at 9 21 31 am](https://cloud.githubusercontent.com/assets/1165719/22518007/e3c8aa32-e85f-11e6-81de-67b161b35840.png)

**Comment by lewismc** [comment]
@Yongyao can you please log a ticket over at Any23?

**Comment by lewismc** [comment]
Issue is open over at https://issues.apache.org/jira/browse/ANY23-304, I'm going to start work on this.

**Comment by lewismc** [comment]
Work is ongoing at https://github.com/apache/any23/pull/33

**Comment by lewismc** [comment]
Resolved as demo'd to both MUDROD and ESIp SemTech groups.
