### ISSUE TITLE
Maven install issue

### ISSUE THREAD

**Issue by Yongyao** [ESIPFed/eskg#4]
After I downloaded the project and ran it with "mvn clean install", it gave me the error below (I am using mac). 

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:25 min
[INFO] Finished at: 2017-02-08T12:09:21-05:00
[INFO] Final Memory: 12M/320M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project eskg: Could not resolve dependencies for project org.esipfed:eskg:jar:1.0-SNAPSHOT: Could not find artifact org.apache.any23.plugins:apache-any23-basic-crawler:jar:2.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 

Also, please see my commit here. 
https://github.com/Yongyao/eskg/commit/681aadb18cef3eee6c0f190ffc228032d29310ff

**Comment by lewismc** [comment]
I'll fix this in a wee bit. Have you downloaded [Any23 master](https://github.com/apache/any23) yet?

**Comment by Yongyao** [comment]
Do I need to download it by myself? I thought it is downloaded by maven automatically

**Comment by lewismc** [comment]
We will be contributing code to Any23 so it's best to download it and lay around with it.
To answer your question, if you can try the PR above then we can determine if the SNAPSHOT repository is correctly defined now. Let me know here please. Thank you
